Create Database TRUE
GO
USE TRUE
GO


--USUARIO

CREATE TABLE USERS(
ID_USER INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NAME_USER VARCHAR(50)NOT NULL,
LASTNAME_USER VARCHAR(50)NOT NULL,
MAIL_USER VARCHAR(50)NOT NULL,
PASSWORD_USER VARCHAR(50)NOT NULL,
PROFILE_PICTURE_USER VARCHAR(500)NOT NULL, --route
PORTRAIT_USER VARCHAR(500)NOT NULL,--route
USERNAME VARCHAR(50) NOT NULL
)



-- PUBLICACIONES

CREATE TABLE POST(
ID_POST INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ROUTE_POST VARCHAR(500),
ID_USER_POST INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
DATE_POST DATETIME NOT NULL,
DESCRIPTION_POST VARCHAR(500)
)


--COMENTARIOS

CREATE TABLE COMMENTS(
ID_COMMENT INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_POST_COMMENT INT FOREIGN KEY REFERENCES POST(ID_POST)NOT NULL,
ID_USER_COMMENT INT FOREIGN KEY REFERENCES USERS(ID_USER)NOT NULL,
COMMENT_TYPE BIT DEFAULT (0) NOT NULL, --0 Comentario, 1 Respuesta
ID_COMMENT_ANSWERED INT FOREIGN KEY REFERENCES COMMENTS(ID_COMMENT),
COMMENT VARCHAR(1000)NOT NULL,
TIMEDATE VARCHAR(100) NOT NULL
)


--LIKES

CREATE TABLE LIKES(
ID_LIKE INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_POST_LIKE INT FOREIGN KEY REFERENCES POST(ID_POST)NOT NULL,
ID_USER_LIKE INT FOREIGN KEY REFERENCES USERS(ID_USER)NOT NULL
)

--DISLIKES

CREATE TABLE DISLIKES(
ID_DISLIKE INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_POST_DISLIKE INT FOREIGN KEY REFERENCES POST(ID_POST)NOT NULL,
ID_USER_DISLIKE INT FOREIGN KEY REFERENCES USERS(ID_USER)NOT NULL
)

--AMIGOS

CREATE TABLE FRIENDS(
ID_FRIENDSHIP INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_USER INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
ID_FRIEND INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
FRIENDSHIP_DATE VARCHAR(100) NOT NULL,
)

--SOLICITUDES DE AMISTAD

CREATE TABLE REQUEST(
ID_REQUEST INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_USER_REQUEST INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
ID_USER_REQUESTED INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
DATE_REQUEST VARCHAR(100) NOT NULL
)

------------------------------------DIRECCION--------------------------------------------------

--PAIS

CREATE TABLE COUNTRY(
ID_COUNTRY INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NAME_COUNTRY VARCHAR(50) NOT NULL
)

--ESTADO

CREATE TABLE STATE(
ID_STATE INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NAME_STATE VARCHAR(50) NOT NULL,
ID_COUNTRY INT FOREIGN KEY REFERENCES COUNTRY(ID_COUNTRY) NOT NULL,
)

--CIUDAD

CREATE TABLE CITY(
ID_CITY INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NAME_CITY VARCHAR(50) NOT NULL,
ID_STATE INT FOREIGN KEY REFERENCES STATE(ID_STATE) NOT NULL,
)

--SECTOR

CREATE TABLE SECTOR(
ID_SECTOR INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NAME_SECTOR VARCHAR(50) NOT NULL,
ID_CITY INT FOREIGN KEY REFERENCES CITY(ID_CITY) NOT NULL,
)

-----------------------------------------------------------------------------------------------

--ENVENTOS

CREATE TABLE EVENT(
ID_EVENT INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_HOST_USER INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
NAME_EVENT VARCHAR (50) NOT NULL,
DESCRIPTION_EVENT VARCHAR (200) NOT NULL,
DATE_EVENT VARCHAR(100) NOT NULL,
--DIRECCION
STREET_EVENT VARCHAR (100) NOT NULL,
APARTMENT_EVENT VARCHAR (50) NOT NULL,
APARTMENT_EXTENSION_EVENT VARCHAR (10),
ID_SECTOR INT FOREIGN KEY REFERENCES SECTOR(ID_SECTOR)NOT NULL
)

--EVENTOS AMIGOS

CREATE TABLE EVENT_USER(
ID_EVENT_USER INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_EVENT INT FOREIGN KEY REFERENCES EVENT(ID_EVENT) NOT NULL,
ID_USER INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
STATUS_EVENT_USER BIT DEFAULT (0) NOT NULL -- 0 UNCONFIRMED, 1 CONFIRMED
)

--TIPO DE NOTIFICACIONES

CREATE TABLE TYPE_NOTIFICATION(
ID_TYPE_NOTIFICATION INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
TYPE VARCHAR(50) NOT NULL --AMIGOS, EVENTOS, NUEVAS PUBLICACIONES
)

--NOTIFICACIONES

CREATE TABLE NOTIFICATION(
ID_NOTIFITACION INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
ID_USER INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
STATUS_NOTIFICATION BIT DEFAULT(1) NOT NULL, --1 NUEVA, 0 LEIDA
TYPE_NOTIFICATION INT FOREIGN KEY REFERENCES TYPE_NOTIFICATION(ID_TYPE_NOTIFICATION) NOT NULL,
MESSAGE VARCHAR(500) NOT NULL
)
GO
--VER PUBLICACIONES DE AMIGOS

create proc GET_POST_PRINCIPAL
@id_user int
as
Select A.ID AS ID_POST, A.POST AS ROUTE, A.ID_USER, A.NAMEUSER, A.POSTDATE AS DATE, A.USERPHOTO, A.CAPTION, ISNULL(B.COUNT_LIKES,0) AS 'LIKES COUNT', ISNULL(B.COUNT_DISLIKES,0)AS 'DISLIKES COUNT', ISNULL(C.ID_LIKE, 0)AS 'MY LIKE', ISNULL(C.ID_DISLIKE, 0)AS 'MY DISLIKE' From
(SELECT P.ID_POST AS ID, P.ROUTE_POST AS POST, P.ID_USER_POST AS ID_USER,
US.NAME_USER + ' ' + US.LASTNAME_USER AS NAMEUSER,
P.DATE_POST AS POSTDATE, US.PROFILE_PICTURE_USER AS USERPHOTO, P.DESCRIPTION_POST AS CAPTION
FROM POST P 
INNER JOIN FRIENDS U ON U.ID_FRIEND = P.ID_USER_POST
LEFT JOIN DISLIKES DL ON DL.ID_POST_DISLIKE = P.ID_POST
LEFT JOIN USERS US ON U.ID_FRIEND = US.ID_USER
WHERE P.ID_USER_POST = (SELECT ID_FRIEND FROM FRIENDS WHERE ID_USER = @id_user))A
LEFT join
(SELECT P.ID_POST AS ID, COUNT(L.ID_USER_LIKE) AS COUNT_LIKES, COUNT(DL.ID_USER_DISLIKE) AS COUNT_DISLIKES FROM POST P
INNER JOIN LIKES L ON P.ID_POST = L.ID_POST_LIKE
INNER JOIN DISLIKES DL ON P.ID_POST = DL.ID_POST_DISLIKE
GROUP BY P.ID_POST
) B ON A.ID = B.ID
LEFT JOIN
(SELECT P.ID_POST, L.ID_LIKE, DL.ID_DISLIKE FROM POST P
INNER JOIN LIKES L ON P.ID_POST = L.ID_POST_LIKE
INNER JOIN DISLIKES DL ON P.ID_POST = DL.ID_POST_DISLIKE
WHERE L.ID_USER_LIKE = @id_user OR DL.ID_USER_DISLIKE = @id_user)C
ON A.ID = C.ID_POST
ORDER BY(A.POSTDATE) DESC
GO

--VER PUBLICACIONES DE USUARIO ESPECIFICO

create proc GET_POST_USER
@id_user int,
@id_user_logged int
as
Select A.ID AS ID_POST, A.POST AS ROUTE, A.ID_USER, A.NAMEUSER, A.POSTDATE AS DATE, A.USERPHOTO, A.CAPTION, ISNULL(B.COUNT_LIKES,0) AS 'LIKES COUNT', ISNULL(B.COUNT_DISLIKES,0)AS 'DISLIKES COUNT', ISNULL(C.ID_LIKE, 0)AS 'MY LIKE', ISNULL(C.ID_DISLIKE, 0)AS 'MY DISLIKE' From
(SELECT P.ID_POST AS ID, P.ROUTE_POST AS POST, P.ID_USER_POST AS ID_USER,
US.NAME_USER + ' ' + US.LASTNAME_USER AS NAMEUSER,
P.DATE_POST AS POSTDATE, US.PROFILE_PICTURE_USER AS USERPHOTO, P.DESCRIPTION_POST AS CAPTION
FROM POST P 
LEFT JOIN DISLIKES DL ON DL.ID_POST_DISLIKE = P.ID_POST
LEFT JOIN USERS US ON P.ID_USER_POST = US.ID_USER
WHERE P.ID_USER_POST = @id_user)A
LEFT join
(SELECT P.ID_POST AS ID, COUNT(L.ID_USER_LIKE) AS COUNT_LIKES, COUNT(DL.ID_USER_DISLIKE) AS COUNT_DISLIKES FROM POST P
INNER JOIN LIKES L ON P.ID_POST = L.ID_POST_LIKE
INNER JOIN DISLIKES DL ON P.ID_POST = DL.ID_POST_DISLIKE
GROUP BY P.ID_POST
)B ON A.ID = B.ID
LEFT JOIN
(SELECT P.ID_POST, L.ID_LIKE, DL.ID_DISLIKE FROM POST P
INNER JOIN LIKES L ON P.ID_POST = L.ID_POST_LIKE
INNER JOIN DISLIKES DL ON P.ID_POST = DL.ID_POST_DISLIKE
WHERE L.ID_USER_LIKE = @id_user_logged OR DL.ID_USER_DISLIKE = @id_user_logged)C
ON A.ID = C.ID_POST
ORDER BY(A.POSTDATE) DESC
GO